# MySQL ?????
spring.datasource.url=jdbc:mysql://localhost:3306/test_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=myuser1
spring.datasource.password=ComplexPass123!

# MyBatis ??
mybatis.mapper-locations=classpath:mapper/*.xml
# Mapper XML???? ??XML????SQL?????????mapper/userMapper.xml ???
#mybatis.type-aliases-package=com.example.demo.model  # ??????

